import jwt from "jsonwebtoken";
import crypto from "crypto";

const jwtSecret: string = "secret|token";

export class JwtService {
  public static generateToken(permissionLevel: Number): any {
    try {
      const salt: string = crypto.randomBytes(16).toString("base64");
      const expiresAt: Date = new Date();

      expiresAt.setHours(expiresAt.getHours() + 8);

      const token: any = jwt.sign({
        id: "007",
        email: "autogenerated@jwt.com",
        permissionLevel: permissionLevel,
        provider: "email",
        name: "bond",
        refreshKey: salt
      }, jwtSecret);

      return token;
    } catch (err) {
      throw err;
    }
  }
}
